### ISSUE TITLE
Rails Drag and Drog Example

### ISSUE THREAD

**Issue by perlmunger** [tim-kos/transloadit-drag-and-drop#1]
HI Tm,

Do you by chance have an example of drag and drop in a rails app--particularly with multiple file upload (simultaneous)?

Thanks.

**Comment by tim-kos** [comment]
Hey there,

I am not sure what you mean exactly. The code is frontend Javascript so can include it into any App, be it in Rails, plain Ruby or PHP. Please let me know if I misunderstood you.

Kind regards,
Tim

Co-Founder Transloadit
@tim_kos

**Comment by perlmunger** [comment]
Right. No I understand that. What I'm wondering is if you have an example that uses this drag and drop example but integrates it with the rails gem, transloadit-rails?

I'm wanting to drag and drop multiple files and have the results added through an active record model once the uploads complete. I was just hoping maybe you had some sample code that already did this.

**Comment by tim-kos** [comment]
Hey Matt,

unfortunately not. : / Rails (or Ruby for that matter) isn't my every day
cup of tea.

Maybe you could ask the authors of the Rails-gem if they can provide any
assistance?

Sorry that I cannot help you. : /

Kind regards,
Tim

Co-Founder Transloadit
@tim_kos

On Tue, Feb 25, 2014 at 3:51 PM, Matt Long notifications@github.com wrote:

> Right. No I understand that. What I'm wondering is if you have an example
> that uses this drag and drop example but integrates it with the rails gem,
> transloadit-rails?
> 
> I'm wanting to drag and drop multiple files and have the results added
> through an active record model once the uploads complete. I was just hoping
> maybe you had some sample code that already did this.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/tim-kos/transloadit-drag-and-drop/issues/1#issuecomment-36014768
> .

## 

Practicing and Teaching the Art of Web Engineering

Tim Koschützki
Director
www.debuggable.com

Debuggable Limited
Friedrichstr. 171
Einstein Palais
10117 Berlin
Mob: +49 (151) 19161166

Commercial Register:  HRB 112594 B  (Charlottenburg, Berlin)
Directors: Tim Koschützki, Felix Geisendörfer
VAT-ID: DE263164617

**Comment by perlmunger** [comment]
Ok. Sorry to bug you. For some reason I had the impression you had worked on the rails gem. Thanks for your time.
