### ISSUE TITLE
Actively Supported?

### ISSUE THREAD

**Issue by brianfeister** [tim-kos/transloadit-drag-and-drop#2]
Hi @tim-kos, I'm wondering if this project is still active.  I was in early stages of implementing it and noticed the parameters in this example code are different from `transloadit2.js` in it's current state.

Just wondering if this is still maintained ... or perhaps drang and drop was rolled into transloadit2.js?

**Comment by tim-kos** [comment]
Hey @brianfeister 

Yeah it's still active, I just never got around to incorporate it into our jQuery plugin.

But yes, please use this project in the meantime.

Kind regards,
Tim

Co-Founder Transloadit
@tim_kos

**Comment by tim-kos** [comment]
Hey @brianfeister 

I just pushed some updates to this project today. It now works with the latest release of the official jQuery plugin, so a custom version is no longer applied.

We have also started working on a new Javascript SDK for Transloadit which will have drag and drop built in by default. You can follow its development here and post your feedback: https://github.com/transloadit/transloadit-js-client
