### ISSUE TITLE
after every upload it doubles the amount of transloadit btns

### ISSUE THREAD

**Issue by jacquescrocker** [tim-kos/transloadit-drag-and-drop#5]
![](http://cl.ly/image/3g0R0E0i2t3Y/content)

using it with the latest transloadit.js (`//assets.transloadit.com/js/jquery.transloadit2-v2-latest.js`)

i think when it calls `.transloadit()` it rebinds the upload btn or something. not sure

**Comment by jacquescrocker** [comment]
seems like this is the code thats doing it. https://github.com/transloadit/jquery-sdk/blob/master/js/lib/jquery.transloadit2.js#L348-L353

how to prevent it?

**Comment by tim-kos** [comment]
This has been fixed now.

Also this project now works with the latest version of the jQuery plugin.
